<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>dtmapi-player-doctor</AssemblyName>
    <RootNamespace>DTMAPI.PlayerDoctor</RootNamespace>
    <Version>$(DtmApiReleaseVersion)</Version>
    <AssemblyVersion>$(DtmApiAssemblyCompatibilityVersion)</AssemblyVersion>
    <FileVersion>$(DtmApiBinaryFileVersion)</FileVersion>
    <InformationalVersion>$(DtmApiReleaseVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DTMAPI.InstallDoctor\DTMAPI.InstallDoctor.csproj" />
  </ItemGroup>
</Project>
