param(
    [switch] $Check,
    [switch] $Quiet,
    [string] $CatalogPath = '',
    [string] $OutputPath = ''
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$repo = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$catalogPathResolved = if ([string]::IsNullOrWhiteSpace($CatalogPath)) {
    Join-Path $repo 'tools\release\dtmapi-product-catalog.json'
}
else {
    $CatalogPath
}
if (-not [System.IO.Path]::IsPathRooted($catalogPathResolved)) {
    $catalogPathResolved = Join-Path $repo $catalogPathResolved
}
$catalogPathResolved = [System.IO.Path]::GetFullPath($catalogPathResolved)

$outputPathResolved = if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    Join-Path $repo 'docs\architecture\managed-product-admission-registry.md'
}
else {
    $OutputPath
}
if (-not [System.IO.Path]::IsPathRooted($outputPathResolved)) {
    $outputPathResolved = Join-Path $repo $outputPathResolved
}
$outputPathResolved = [System.IO.Path]::GetFullPath($outputPathResolved)

if (-not (Test-Path -LiteralPath $catalogPathResolved -PathType Leaf)) {
    throw "Product Catalog is missing: $catalogPathResolved"
}

$catalog = [System.IO.File]::ReadAllText($catalogPathResolved, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
$products = @($catalog.products | Where-Object {
    $kindProperty = $_.PSObject.Properties['codeModKind']
    $null -ne $kindProperty -and [string]$kindProperty.Value -ceq 'Advanced'
})
if ($products.Count -eq 0) {
    throw 'Product Catalog contains no managed Advanced admission rows.'
}

foreach ($product in $products) {
    foreach ($field in @('catalogId', 'uniqueId', 'nativeOwnership', 'referencePolicyId', 'sourceManifest')) {
        $property = $product.PSObject.Properties[$field]
        if ($null -eq $property -or [string]::IsNullOrWhiteSpace([string]$property.Value)) {
            throw "Advanced admission row '$([string]$product.catalogId)' is missing '$field'."
        }
    }
    if ([string]$product.nativeOwnership -cne 'ProductNative') {
        throw "Advanced admission row '$([string]$product.catalogId)' does not declare ProductNative ownership."
    }
}

function ConvertTo-MarkdownCell {
    param([Parameter(Mandatory = $true)] [string] $Value)
    return $Value.Replace('|', '\|')
}

$lines = New-Object 'System.Collections.Generic.List[string]'
foreach ($line in @(
    '<!-- Generated by tools/scripts/generate-managed-product-admission-registry.ps1 from tools/release/dtmapi-product-catalog.json. Do not edit rows manually. -->',
    '# Managed Product Admission Registry',
    '',
    'This version-independent registry is the canonical projection of the Catalog-managed receipt Advanced product lane. A row exists exactly when the Product Catalog row declares `codeModKind: Advanced`; policy and physical ownership remain Catalog facts. Internal NativeContractVersion=1 authors use SDK-generated local-host provenance and do not require Catalog rows; see [native references](../../author-sdk/NATIVE-REFERENCES.md).',
    '',
    'Admission means that the named identity may use the tracked managed Advanced/ProductNative lane with its generated policy, receipt and package. It does **not** mean that the product is public, subscribed, installed, enabled, loaded, currently compatible with a player build, or authorized for a new release.',
    '',
    'Current public/subscription membership is deliberately absent. Read the [Product Catalog](../../tools/release/dtmapi-product-catalog.json), [current subscription manifest](../../tools/release/current-subscription-manifest.json), and the latest release Update named by that manifest''s `authority.latestReleaseUpdate` for those facts. A future upload authorization is a separate Catalog `releaseStop` fact. The frozen [Batch 6 / 0.5.5 historical annex](batch6-managed-mod-identity-contract.md) is audit evidence only.',
    '',
    '## Generated Admission Rows',
    '',
    '| Catalog ID | UniqueID | Ownership | Reference policy | Source manifest |',
    '| --- | --- | --- | --- | --- |'
)) {
    $lines.Add($line) | Out-Null
}

foreach ($product in $products) {
    $lines.Add(('| `{0}` | `{1}` | `{2}` | `{3}` | `{4}` |' -f
        (ConvertTo-MarkdownCell ([string]$product.catalogId)),
        (ConvertTo-MarkdownCell ([string]$product.uniqueId)),
        (ConvertTo-MarkdownCell ([string]$product.nativeOwnership)),
        (ConvertTo-MarkdownCell ([string]$product.referencePolicyId)),
        (ConvertTo-MarkdownCell ([string]$product.sourceManifest)))) | Out-Null
}

foreach ($line in @(
    '',
    '## Regeneration',
    '',
    'Regenerate after an authorized Catalog admission change:',
    '',
    '```powershell',
    'tools/scripts/generate-managed-product-admission-registry.ps1',
    'tools/scripts/generate-managed-product-admission-registry.ps1 -Check',
    '```',
    '',
    'A product beyond these generated rows remains blocked until its own bounded admission changes the Catalog and the SDK/tracked-policy gates. Hand-written manifests, receipts or packages never create admission.'
)) {
    $lines.Add($line) | Out-Null
}

$expected = ($lines.ToArray() -join "`n") + "`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $outputPathResolved -PathType Leaf)) {
        Write-Host "Managed product admission registry is missing: $outputPathResolved" -ForegroundColor Red
        exit 1
    }
    $actual = [System.IO.File]::ReadAllText($outputPathResolved, [System.Text.Encoding]::UTF8).Replace("`r`n", "`n")
    if ($actual -cne $expected) {
        Write-Host 'Managed product admission registry is stale. Regenerate it from the Product Catalog.' -ForegroundColor Red
        $actualLines = @($actual -split "`n")
        $expectedLines = @($expected -split "`n")
        $maximumLineCount = [Math]::Max($actualLines.Count, $expectedLines.Count)
        for ($index = 0; $index -lt $maximumLineCount; $index++) {
            $actualLine = if ($index -lt $actualLines.Count) { $actualLines[$index] } else { '<missing>' }
            $expectedLine = if ($index -lt $expectedLines.Count) { $expectedLines[$index] } else { '<missing>' }
            if ($actualLine -cne $expectedLine) {
                Write-Host "First difference at line $($index + 1)." -ForegroundColor Red
                Write-Host "Expected: $expectedLine" -ForegroundColor Red
                Write-Host "Actual:   $actualLine" -ForegroundColor Red
                break
            }
        }
        exit 1
    }
    if (-not $Quiet) {
        Write-Host "Managed product admission registry: OK ($($products.Count) rows)" -ForegroundColor Green
    }
    exit 0
}

$outputDirectory = Split-Path -Parent $outputPathResolved
if (-not (Test-Path -LiteralPath $outputDirectory -PathType Container)) {
    [System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
}
[System.IO.File]::WriteAllText($outputPathResolved, $expected, (New-Object System.Text.UTF8Encoding($false)))
if (-not $Quiet) {
    Write-Host "Generated managed product admission registry: $outputPathResolved ($($products.Count) rows)" -ForegroundColor Green
}
