using DolocTown.GameData;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace DolocTown;

public class DungeonHandle : MonoBehaviour
{
	[SerializeField]
	public bool autoGenerateData = true;

	[SerializeField]
	public RoomHandle entranceRoom;

	[SerializeField]
	public EnvBackgroundSO _backgroundSo;

	[SerializeField]
	public Tilemap baseMap;

	[SerializeField]
	public Tilemap dctMap;

	[SerializeField]
	public Tilemap ptMap;

	[SerializeField]
	public Tilemap resourceControlLayerTree;

	[SerializeField]
	public Tilemap resourceControlLayerOther;

	[SerializeField]
	public Tilemap vegetationControlLayer;

	[SerializeField]
	public Tilemap monsterLayer;

	[SerializeField]
	public Tilemap envObjectLayer;

	[SerializeField]
	public Tilemap collisionLayer;

	[SerializeField]
	public Transform subRoomContainer;

	public Tilemap TilemapBase => baseMap;

	private void Start()
	{
		DisableEditorLayers();
	}

	private void DisableEditorLayers()
	{
		if (resourceControlLayerOther != null)
		{
			resourceControlLayerOther.gameObject.SetActive(value: false);
		}
		if (resourceControlLayerTree != null)
		{
			resourceControlLayerTree.gameObject.SetActive(value: false);
		}
		if (vegetationControlLayer != null)
		{
			vegetationControlLayer.gameObject.SetActive(value: false);
		}
		if (monsterLayer != null)
		{
			monsterLayer.gameObject.SetActive(value: false);
		}
		if (envObjectLayer != null)
		{
			envObjectLayer.gameObject.SetActive(value: false);
		}
		if (collisionLayer != null)
		{
			collisionLayer.gameObject.SetActive(value: false);
		}
	}

	public RoomHandle GetSubRoom(string name)
	{
		Transform transform = subRoomContainer.Find(name);
		if (transform != null)
		{
			return transform.GetComponent<RoomHandle>();
		}
		return null;
	}
}
