// <auto-generated />
using System;
using System.Collections.Generic;

namespace Yuuka.DTMAPI.FishBreedingAssistant
{
    internal sealed class FishRoeInfo
    {
        internal readonly string FishId;
        internal readonly string FishTitle;
        internal readonly string RoeTitle;
        internal readonly string IncubateText;
        internal readonly string GrowText;
        internal readonly string ParentSummary;

        internal FishRoeInfo(string fishId, string fishTitle, string roeTitle, string incubateText, string growText, string parentSummary)
        {
            FishId = fishId;
            FishTitle = fishTitle;
            RoeTitle = roeTitle;
            IncubateText = incubateText;
            GrowText = growText;
            ParentSummary = parentSummary;
        }
    }

    internal static class FishBreedingLookup
    {
        private static readonly Dictionary<string, FishRoeInfo> ByFishId = new Dictionary<string, FishRoeInfo>(StringComparer.Ordinal)
        {
            { "fish", new FishRoeInfo("fish", "鱼", "鱼卵", "4 小时", "6 小时", "自交：鱼（100.00%）") },
            { "carp", new FishRoeInfo("carp", "鲤鱼", "鱼卵", "4 小时", "12 小时", "自交：鲤鱼（100.00%）；默认产出：锦鲤（25.00%）；默认产出：闪亮黄金鱼（19.61%）") },
            { "koi", new FishRoeInfo("koi", "锦鲤", "鱼卵", "12 小时", "1 天", "自交：锦鲤（50.00%）；默认产出：闪亮黄金鱼（39.22%）；杂交：鲤鱼 ≥ 3（标准配比 66.67%）") },
            { "rainbow_trout", new FishRoeInfo("rainbow_trout", "虹鳟鱼", "鱼卵", "4 小时", "12 小时", "自交：虹鳟鱼（100.00%）") },
            { "hoplias", new FishRoeInfo("hoplias", "牙鱼", "鱼卵", "4 小时", "12 小时", "自交：牙鱼（100.00%）") },
            { "catfish", new FishRoeInfo("catfish", "鲶鱼", "鱼卵", "4 小时", "12 小时", "自交：鲶鱼（100.00%）") },
            { "grass_carp", new FishRoeInfo("grass_carp", "草鱼", "鱼卵", "4 小时", "12 小时", "自交：草鱼（75.00%）") },
            { "slimefish", new FishRoeInfo("slimefish", "水生变形虫", "鱼卵", "4 小时", "12 小时", "未找到可产出来源") },
            { "sturgeon", new FishRoeInfo("sturgeon", "鲟鱼", "鱼卵", "3 天", "7 天", "自交：鲟鱼（100.00%）") },
            { "loach", new FishRoeInfo("loach", "泥鳅", "鱼卵", "4 小时", "12 小时", "未找到可产出来源") },
            { "snail", new FishRoeInfo("snail", "田螺", "鱼卵", "4 小时", "12 小时", "未找到可产出来源") },
            { "golden_fish", new FishRoeInfo("golden_fish", "闪亮黄金鱼", "鱼卵", "2 天", "5 天", "自交：闪亮黄金鱼（39.22%）；杂交：鲤鱼 = 6 + 锦鲤 = 6（标准配比 10.00%）") },
            { "ricefield_eel", new FishRoeInfo("ricefield_eel", "黄鳝", "鱼卵", "12 小时", "1 天", "自交：黄鳝（100.00%）") },
            { "pike", new FishRoeInfo("pike", "狗鱼", "鱼卵", "12 小时", "1 天", "自交：狗鱼（100.00%）；默认产出：蓝狗鱼（25.00%）") },
            { "sardine", new FishRoeInfo("sardine", "沙丁鱼", "鱼卵", "4 小时", "12 小时", "自交：沙丁鱼（100.00%）；默认产出：黑背沙丁鱼（25.00%）") },
            { "seabass", new FishRoeInfo("seabass", "鲈鱼", "鱼卵", "4 小时", "12 小时", "自交：鲈鱼（100.00%）") },
            { "codfish", new FishRoeInfo("codfish", "鳕鱼", "鱼卵", "12 小时", "1 天", "自交：鳕鱼（100.00%）；默认产出：红鳕鱼（25.00%）") },
            { "tuna", new FishRoeInfo("tuna", "金枪鱼", "鱼卵", "1 天", "2 天", "自交：金枪鱼（75.00%）") },
            { "eel", new FishRoeInfo("eel", "鳗鱼", "鱼卵", "12 小时", "1 天", "自交：鳗鱼（100.00%）") },
            { "fluorescent_eel", new FishRoeInfo("fluorescent_eel", "荧光鳗鱼", "鱼卵", "1 天", "2 天", "自交：荧光鳗鱼（100.00%）") },
            { "skeleton_fish", new FishRoeInfo("skeleton_fish", "拟态骨架鱼", "鱼卵", "12 小时", "1 天", "自交：拟态骨架鱼（100.00%）") },
            { "shrimp", new FishRoeInfo("shrimp", "虾", "鱼卵", "4 小时", "12 小时", "未找到可产出来源") },
            { "salmon", new FishRoeInfo("salmon", "鲑鱼", "鱼卵", "12 小时", "1 天", "自交：鲑鱼（100.00%）；默认产出：大马哈鱼（50.00%）") },
            { "nightbone_fish", new FishRoeInfo("nightbone_fish", "黑夜骨架鱼", "鱼卵", "12 小时", "1 天", "自交：黑夜骨架鱼（97.00%）；杂交：拟态骨架鱼 ≥ 3（标准配比 66.67%）") },
            { "silverlight_eel", new FishRoeInfo("silverlight_eel", "银光鳗", "鱼卵", "12 小时", "1 天", "自交：银光鳗（99.00%）；杂交：鳗鱼 ≥ 6（标准配比 50.00%）") },
            { "humpback_salmon", new FishRoeInfo("humpback_salmon", "大马哈鱼", "鱼卵", "1 天", "2 天", "自交：大马哈鱼（50.00%）；杂交：鲑鱼 ≥ 6（标准配比 50.00%）") },
            { "crimson_cod", new FishRoeInfo("crimson_cod", "红鳕鱼", "鱼卵", "12 小时", "1 天", "自交：红鳕鱼（75.00%）；杂交：鳕鱼 ≥ 3（标准配比 66.67%）") },
            { "azure_pike", new FishRoeInfo("azure_pike", "蓝狗鱼", "鱼卵", "12 小时", "1 天", "自交：蓝狗鱼（75.00%）；杂交：狗鱼 ≥ 3（标准配比 66.67%）") },
            { "blackback_sardine", new FishRoeInfo("blackback_sardine", "黑背沙丁鱼", "鱼卵", "4 小时", "12 小时", "自交：黑背沙丁鱼（75.00%）；杂交：沙丁鱼 ≥ 5 + 鲶鱼 = 1（标准配比 66.67%）") },
            { "monarch_tuna", new FishRoeInfo("monarch_tuna", "帝王金枪鱼", "鱼卵", "3 天", "7 天", "自交：帝王金枪鱼（96.77%）；杂交：金枪鱼 ≥ 5 + 闪亮黄金鱼 ≥ 2（标准配比 25.00%）") },
            { "leaf_slug", new FishRoeInfo("leaf_slug", "草叶蛞蝓", "鱼卵", "12 小时", "1 天", "杂交：草鱼 ≥ 3 + 水生变形虫 ≥ 3（标准配比 50.00%）") },
            { "mist_eel", new FishRoeInfo("mist_eel", "雾隐鳝", "鱼卵", "12 小时", "1 天", "自交：雾隐鳝（75.00%）；杂交：泥鳅 ≥ 4 + 黄鳝 ≥ 4（标准配比 50.00%）") },
            { "terror_fish", new FishRoeInfo("terror_fish", "恐鱼", "鱼卵", "12 小时", "1 天", "自交：恐鱼（75.00%）；杂交：牙鱼 = 3 + 狗鱼 = 3（标准配比 25.00%）") },
            { "abyss_lantern_seabass", new FishRoeInfo("abyss_lantern_seabass", "渊潜灯笼鲈", "鱼卵", "1 天", "2 天", "自交：渊潜灯笼鲈（75.00%）；杂交：鲈鱼 ≥ 4 + 荧光鳗鱼 ≥ 4（标准配比 50.00%）") },
        };

        internal static bool TryGet(string fishId, out FishRoeInfo info)
        {
            if (string.IsNullOrEmpty(fishId))
            {
                info = null;
                return false;
            }

            return ByFishId.TryGetValue(fishId, out info);
        }
    }
}
