<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Unity.Addressables">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UniTask.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/DOTween.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/YarnSpinner.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner.Compiler">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/YarnSpinner.Compiler.dll</HintPath>
    </Reference>
    <Reference Include="YarnSpinner.Unity">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/YarnSpinner.Unity.dll</HintPath>
    </Reference>
    <Reference Include="ParadoxNotion">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/ParadoxNotion.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="Febucci.TextAnimator.Runtime">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Febucci.TextAnimator.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="AK.Wwise.Unity.MonoBehaviour">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/AK.Wwise.Unity.MonoBehaviour.dll</HintPath>
    </Reference>
    <Reference Include="AK.Wwise.Unity.API">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/AK.Wwise.Unity.API.dll</HintPath>
    </Reference>
    <Reference Include="AK.Wwise.Unity.Addressables">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/AK.Wwise.Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="UnityUIExtensions">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityUIExtensions.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/Sirenix.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>research/reverse/patch_test_20260517_09605/DolocTown_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>