<Project>
  <PropertyGroup>
    <DtmApiVersionAuthoritySchema>1</DtmApiVersionAuthoritySchema>
    <DtmApiReleaseVersion>0.7.0</DtmApiReleaseVersion>
    <DtmApiBinaryFileVersion>0.7.0.0</DtmApiBinaryFileVersion>
    <DtmApiAssemblyCompatibilityVersion>0.5.3.0</DtmApiAssemblyCompatibilityVersion>
  </PropertyGroup>
</Project>
