namespace DolocTown;

public enum OperationEventType
{
	NONE,
	JUMP,
	DOUBLE_JUMP,
	SPRINT,
	MOVE,
	JUMP_DOWN_PLATFORM,
	CLIMB,
	SCROLL_SELECTED_ITEM,
	SCROLL_BACKPACK_LINE,
	USE_TOOL,
	USE_ITEM,
	USE_CASE_EQUIPMENT,
	ENTER_BUILDING,
	OPEN_MAP_PANEL,
	OPEN_MISSION_PANEL,
	OPEN_TECH_TREE_PANEL,
	OPEN_MAIN_MENU_PANEL,
	OPEN_BACKPACK_PANEL,
	SELECTED_DRONE_ITEM,
	EQUIP_DRONE,
	EQUIP_ACTIVE_ITEM,
	OPEN_DRONE_PANEL,
	FIRE_DRONE,
	SWITCH_GUN_MODE,
	FELL_EQUIPMENT,
	FELL_PLATFORM,
	EQUIP_PASSIVE_ITEM
}
